Repository ideoxan/ideoxan, pull requests merged in 2020-10, with the labels that each got.

#73 Fix Spacing and Alignment of Profile Settings
  content/www/static/css/site.css
Labels: Hacktoberfest, Website, bug (low)

#77 add default config file
  .gitignore
  config.default.json
  index.js
  src/apps/main.js
Labels: Hacktoberfest, Other, Server, enhancement

#88 Splitting up test files into tests/routes.test.js and tests/general.test.js
  tests/general.test.js
  tests/routes.test.js
Labels: Hacktoberfest, Other, documentation, enhancement

#94 Server Launcher/Application Loader Visual Improvements
  index.js
  src/apps/main.js
Labels: Hacktoberfest, Server, enhancement

#99 Added translation features to the main website.
  config.default.json
  content/www/locales/de.json
  content/www/locales/en.json
  content/www/locales/es.json
  content/www/locales/fr.json
  content/www/locales/hi.json
  content/www/locales/id.json
  content/www/locales/ru.json
  content/www/locales/sv.json
  content/www/static/css/site.css
  content/www/views/about.ejs
  content/www/views/catalogue.ejs
  content/www/views/completed.ejs
  content/www/views/coursedescription.ejs
  content/www/views/error.ejs
  content/www/views/index.ejs
  content/www/views/login.ejs
  content/www/views/partials/boxgrid.ejs
  content/www/views/partials/footer.ejs
  content/www/views/partials/header200620.ejs
  content/www/views/partials/headeruser.ejs
  content/www/views/partials/nav.ejs
  content/www/views/partials/progress.ejs
  content/www/views/privacy.ejs
  content/www/views/signup.ejs
  content/www/views/tos.ejs
  content/www/views/user.ejs
  content/www/views/usersettings.ejs
  package-lock.json
  package.json
  src/apps/main.js
  src/routes/general/finishCourse.js
Labels: Hacktoberfest, Other, Server, Website, enhancement

#93 Modified the user dropdown menu
  content/www/static/css/site.css
  content/www/views/partials/nav.ejs
Labels: Hacktoberfest, Website, enhancement

#100 Formatted and Added Comments to Code
  index.js
  src/apps/main.js
Labels: Hacktoberfest, Server, documentation

#108 added partial portuguese translations
  content/www/locales/pt.json
Labels: Hacktoberfest, Translation, Website

#106 German Translation
  content/www/locales/de.json
Labels: Hacktoberfest, Translation, Website

#109 translate to tr
  content/www/locales/tr.json
Labels: Hacktoberfest, Translation, Website
